### ISSUE TITLE
Bind lost when I reopen the file

### ISSUE THREAD

**Issue by ambivalenzia** [artellblender/auto_rig#24]
Hello

[humanoid-v007.blend.zip](https://github.com/artellblender/auto_rig/files/3553064/humanoid-v007.blend.zip)

After Binding the weight painting works as expected, but when I save the file and reopen it, the binding is gone. When I try to Bind it again, the result looks terrible.  
I work on Blender 2.8 (official build) on Linux Mint. Python Code is set to execute automatically. 

Thanks for your work! 

Best regards

**Comment by artellblender** [comment]
I haven't been able to reproduce the issue with the given file. Saving and reopening it kept the mesh bound to the rig, no skinning data were lost.
I can remember a similar issue when using the MBLab addon, which is what you used as far as I understand. It seems there's a back process script that changes skinning/modifiers when loading the file. Please try to uninstall or disable the MBLab addon, and see if it works.
I close the issue for now, feel free to reopen it if the bug is still there but it does not seem to be an Auto-Rig Pro bug.
