### ISSUE TITLE
Facial Rigging not working properly inside the mouth.

### ISSUE THREAD

**Issue by dsguffey** [artellblender/auto_rig#34]
Everything else is working as expected, but around the mouth there's tons of problems. Auto Rigger doesn't seem to have any idea where the teeth/gums and tongue are. Is this a failure on my part in terms of placing the markers, or is it just assumed that the user will have to fix their placement manually? Also, probably for similar reasons, the weight painting is just all over the place there. I can't find any auto-rigger tutorials for the inside of the mouth specifically.  Does one exist, or could Artell create one?

**Comment by LFADesign** [comment]
For mouth rigging, separate everything: Upper Teeth, Lower Teeth, Tongue, Mouth Bag (If present). Use vertex groups in Edit Mode instead of weight painting: Upper Teeth assigned to Head. Lower teeth and tongue assigned to jaw. Furthermore, split to tongue into sections 1, 2 and 3 assigned respectively to Tongue 01 , Tongue 02 and Tongue 03 (tip). If your character has mouth bag, on side view, select upper vertices close to the lips and assign to Head. Lower vertices to the Jaw.
If lips are getting glued together, perhaps you imported your character as obj. Use fbx instead.

**Comment by artellblender** [comment]
Facial skinning is generally too delicate for the automatic binding engines:
http://lucky3d.fr/auto-rig-pro/doc/faq.html#skinning-issues-after-binding
