### ISSUE TITLE
Remapping results in a deformed armature 

### ISSUE THREAD

**Issue by p23power** [artellblender/auto_rig#7]
Hi,

Using a human mesh from MakeHuman, I follow the steps in the documentation (http://www.lucky3d.fr/auto-rig-pro/doc/auto_rig.html) 
[base2.zip](https://github.com/artellblender/auto_rig/files/2896865/base2.zip)

(a) using the auto-rig smart etc.  (b) load a bvh file (c) remap.  It always results in a deformed armature with the mesh in a mess.  Please can you indicate what I am doing wrong.  I attach a blender file that contains my mesh, armature and animation.

* I have tried many bvh files (from https://github.com/Abhinav2107/cs775-a1/tree/master/bvh and https://sites.google.com/a/cgspeed.com/cgspeed/motion-capture/daz-friendly-release)
* I have tried tweaking the bvh data
* I have tried using the auto-rig "interactive tweak" values

Auto-rig 612711d40afb4a10c1f50ea9e63ac1ff.zip
Blender 2.79b  (2018-03-22)
Window 10 (build 17134)

![image](https://user-images.githubusercontent.com/21229083/53287481-aece4b00-3774-11e9-8913-931cbd6ef2b5.png)

**Comment by p23power** [comment]
In the initial comment, base2.zip is the blender file

**Comment by artellblender** [comment]
Hello,
This is an issue of the BVH armature, which have different bones orientations in rest pose / in pose mode.
The axis orientation of the Hips and ToSpine bones don't match: in rest pose, Hips has Z pointing rightward and Y upward, while in the animation, Z is pointing leftward and Y downward. So the target armature does the same when retargetting, flipping the c_root_master.x and c_spine_01 bones axis.
To fix it, use the "Redefine Rest Pose" button: make sure to rotate the Hips and ToSpine bones so that they match the rotation when they're animated.
